import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LoggedIn from '../ui/layouts/index/LoggedIn'
import { GetServerSidePropsContext, NextPage } from 'next'
import { Auth } from '../lib/Auth'
import { PageProps } from '../types/PageProps'
import { AccountStatus } from '@prisma/client'

const Home: NextPage<PageProps> = ({ signedIn, status }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoggedIn />
    </div>
  )
}

export default Home

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const auth = new Auth()
  const user = await auth.getUser(context)
 
  if (!user || !user.sub) {
    return {
      props: {
        signedIn: false,
        status: null
      }
    }
  }

  return {
    props: {
      signedIn: true
    }
  }

}
