import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LoggedIn from '../ui/layouts/index/LoggedIn'
import { GetServerSidePropsContext } from 'next'
import { Auth } from '../lib/Auth'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoggedIn />
    </div>
  )
}

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const auth = new Auth()
  const session = await auth.authenticate(context.req, context.res)
  console.log(session)
}
