import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Signup.module.css'
import React, { useState } from 'react'


const Signup = () => {
  const [username, setUsername] = useState<string>('')
  const [password, setPassword] = useState<string>('')
  const [confirmPassword, setConfirmPassword] = useState<string>('')

  const submitHandler = async (e: any) => {
    e.preventDefault()
    const newUser = await fetch('/api/sign-up', {
      method: 'post',
      body: JSON.stringify({
        username,
        password,
        confirmPassword
      })
    })
    const res = await newUser.json()
    console.log(res)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={submitHandler}>
        <h2>Signup</h2>
        <input value={username} onChange={(e) => setUsername(e.target.value)} />
        <input value={password} onChange={(e) => setPassword(e.target.value)} />
        <input value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} />
        <button type="submit">click</button>
      </form>
    </div>
  )
}

export default Signup