import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Signup.module.css'



const Signup = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Welcome</h2>
      <h3>What will you be signing up as?</h3>
    </div>
  )
}

export default Signup